import { FoodItem, Category } from "@/types";

export const FALLBACK_CATEGORIES: Category[] = [
  {
    id: "cat-tiffins",
    name: "Tiffins & Breakfast",
    slug: "tiffins",
    description: "Steaming hot idlys, crunchy wadas, pooris, and bondas served with fresh chutneys and piping hot sambar.",
    icon: "Sparkles",
    displayOrder: 1,
    isActive: true,
    _count: { items: 10 },
  },
  {
    id: "cat-dosa",
    name: "Dosa & Pesara Specials",
    slug: "dosa",
    description: "Crispy golden dosas & pesarattus roasted on cast-iron tavas with desi ghee, onion, paneer, and fiery karam.",
    icon: "Flame",
    displayOrder: 2,
    isActive: true,
    _count: { items: 17 },
  },
  {
    id: "cat-evening",
    name: "Only Evening Specials",
    slug: "evening-specials",
    description: "Hot soft chapatis and flaky layered parathas served exclusively during evening sessions.",
    icon: "UtensilsCrossed",
    displayOrder: 3,
    isActive: true,
    _count: { items: 2 },
  },
  {
    id: "cat-veg-noodles",
    name: "Veg Noodles",
    slug: "veg-noodles",
    description: "Street-style wok-tossed noodles with fresh vegetables and signature spices.",
    icon: "Soup",
    displayOrder: 4,
    isActive: true,
    _count: { items: 3 },
  },
  {
    id: "cat-nonveg-noodles",
    name: "Non-Veg Noodles",
    slug: "nonveg-noodles",
    description: "Sizzling high-flame wok noodles with chicken chunks, egg, and spicy garlic glaze.",
    icon: "Soup",
    displayOrder: 5,
    isActive: true,
    _count: { items: 3 },
  },
  {
    id: "cat-veg-rice",
    name: "Veg Fried Rice",
    slug: "veg-rice",
    description: "Fragrant basmati rice wok-fried with crisp garden vegetables, paneer, baby corn, and mushrooms.",
    icon: "Flame",
    displayOrder: 6,
    isActive: true,
    _count: { items: 5 },
  },
  {
    id: "cat-nonveg-rice",
    name: "Non-Veg Fried Rice",
    slug: "nonveg-rice",
    description: "High-flame wok tossed basmati rice with tender chicken, egg, and spicy chilli chicken.",
    icon: "Flame",
    displayOrder: 7,
    isActive: true,
    _count: { items: 3 },
  },
  {
    id: "cat-veg-starters",
    name: "Veg Starters",
    slug: "veg-starters",
    description: "Crispy Veg Manchurian, Paneer Manchurian, and Chilli Paneer cooked fresh.",
    icon: "Sparkles",
    displayOrder: 8,
    isActive: true,
    _count: { items: 3 },
  },
  {
    id: "cat-nonveg-starters",
    name: "Non-Veg Starters",
    slug: "nonveg-starters",
    description: "Chicken Manchurian, Chilli Chicken, Egg Manchurian, and rich Mughlai Chicken.",
    icon: "Flame",
    displayOrder: 9,
    isActive: true,
    _count: { items: 4 },
  },
];

export const FALLBACK_MENU_ITEMS: FoodItem[] = [
  // =========================================================================
  // 1. TIFFINS (Exact Menu Board Tariff: upahar_tiffins_menu.jpg)
  // =========================================================================
  {
    id: "idly-4",
    name: "Idly (4)",
    slug: "idly-4",
    description: "Four cloud-soft steamed rice and urad dal cakes, served piping hot with freshly ground peanut chutney and drumstick sambar.",
    price: 30,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-tiffins",
    category: FALLBACK_CATEGORIES[0],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "2-3 mins",
    portionSize: "4 Steamed Idlis",
    ingredients: "Fermented rice batter, Urad dal, Sambar, Chutney",
    displayOrder: 1,
  },
  {
    id: "tatte-idly",
    name: "Tatte Idly",
    slug: "tatte-idly",
    description: "Signature wide, fluffy plate-shaped tatte idly steamed to spongy tenderness and served steaming with fragrant podi and sambar.",
    price: 25,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-tiffins",
    category: FALLBACK_CATEGORIES[0],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "3-5 mins",
    portionSize: "1 Jumbo Tatte Idly",
    ingredients: "Stone-ground rice batter, Chutneys, Sambar",
    displayOrder: 2,
  },
  {
    id: "sambar-idly-3",
    name: "Sambar Idly (3)",
    slug: "sambar-idly-3",
    description: "Three soft idlis immersed completely in a bowl of piping hot, spiced drumstick sambar with melting ghee.",
    price: 30,
    image: "/sambar-idli.jpg",
    categoryId: "cat-tiffins",
    category: FALLBACK_CATEGORIES[0],
    isVeg: true,
    isSpicy: true,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "2-3 mins",
    portionSize: "3 Idlis soaked in Sambar",
    ingredients: "Steamed idlis, Drumstick sambar, Coriander",
    displayOrder: 3,
  },
  {
    id: "citti-idly",
    name: "Citti Idly",
    slug: "citti-idly",
    description: "Soft, Steamed Mini Idlies tossed with Ghee Podi, served with coconut chutney, tomato chutney, and fragrant podi ghee.",
    price: 40,
    image: "/images/upahar_chitti_idly.jpg",
    categoryId: "cat-tiffins",
    category: FALLBACK_CATEGORIES[0],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "3-5 mins",
    portionSize: "Bowl of Button Idlis with Ghee Podi",
    ingredients: "Mini idlis, Pure Desi Ghee, Roasted podi, 3 Chutneys",
    displayOrder: 4,
  },
  {
    id: "ghee-podi-idly-3",
    name: "Ghee Podi Idly (3)",
    slug: "ghee-podi-idly-3",
    description: "Three steaming idlis tossed generously in authentic roasted gun powder (podi) and pure fragrant ghee.",
    price: 35,
    image: "/chitti-idly.jpg",
    categoryId: "cat-tiffins",
    category: FALLBACK_CATEGORIES[0],
    isVeg: true,
    isSpicy: true,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "3-5 mins",
    portionSize: "3 Idlis with Ghee Podi",
    ingredients: "Steamed idlis, Pure Desi Ghee, Roasted karam podi",
    displayOrder: 5,
  },
  {
    id: "tawa-idly",
    name: "Tawa Idly",
    slug: "tawa-idly",
    description: "Idlis sliced and stir-fried on a roaring hot cast-iron tawa with onions, curry leaves, crushed spices, and ghee.",
    price: 50,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-tiffins",
    category: FALLBACK_CATEGORIES[0],
    isVeg: true,
    isSpicy: true,
    isBestseller: false,
    isSignature: true,
    isAvailable: true,
    prepTime: "5-7 mins",
    portionSize: "1 Plate spiced tawa idly",
    ingredients: "Idly cubes, Onions, Green chillies, Ghee, Masala",
    displayOrder: 6,
  },
  {
    id: "bonda-4",
    name: "Bonda (4)",
    slug: "bonda-4",
    description: "Crisp on the outside, feather-light and fluffy inside Mysore style bondas served with ginger and coconut chutney.",
    price: 30,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-tiffins",
    category: FALLBACK_CATEGORIES[0],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "3-5 mins",
    portionSize: "4 Crisp Bondas",
    ingredients: "Fermented batter, Cumin seeds, Ginger, Green chillies",
    displayOrder: 7,
  },
  {
    id: "poori-2",
    name: "Poori (2)",
    slug: "poori-2",
    description: "Two golden puffed deep-fried wheat pooris served with flavorful potato kurma/saggu and chutney.",
    price: 30,
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-tiffins",
    category: FALLBACK_CATEGORIES[0],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "4-6 mins",
    portionSize: "2 Pooris + Potato Masala",
    ingredients: "Whole wheat flour, Potato kurma, Onion masala",
    displayOrder: 8,
  },
  {
    id: "wada-3",
    name: "Wada (3)",
    slug: "wada-3",
    description: "Three deep golden, crunchy medu wadas tempered with black pepper and curry leaves, served with chutney & sambar.",
    price: 30,
    image: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-tiffins",
    category: FALLBACK_CATEGORIES[0],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "3-5 mins",
    portionSize: "3 Crispy Medu Wadas",
    ingredients: "Urad dal, Peppercorns, Ginger, Curry leaves",
    displayOrder: 9,
  },
  {
    id: "sambar-wada-2",
    name: "Sambar Wada (2)",
    slug: "sambar-wada-2",
    description: "Two crisp wadas submerged in steaming hot drumstick sambar until tender, garnished with fresh onions and coriander.",
    price: 30,
    image: "https://images.unsplash.com/photo-1589301773859-a54823eb39e0?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-tiffins",
    category: FALLBACK_CATEGORIES[0],
    isVeg: true,
    isSpicy: true,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "2-4 mins",
    portionSize: "2 Wadas in Sambar Bowl",
    ingredients: "Crisp wadas, Spiced sambar, Fresh onions",
    displayOrder: 10,
  },

  // =========================================================================
  // 2. DOSA & PESARA (Exact Menu Board Tariff: upahar_tiffins_menu.jpg)
  // =========================================================================
  {
    id: "plain-dosa",
    name: "Plain Dosa",
    slug: "plain-dosa",
    description: "Traditional thin golden crepe roasted on cast iron with pure ghee & oil, served with coconut chutney & sambar.",
    price: 30,
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "4-6 mins",
    portionSize: "1 Large Crisp Dosa",
    ingredients: "Stone-ground fermented batter, Ghee, Chutneys",
    displayOrder: 11,
  },
  {
    id: "onion-dosa",
    name: "Onion Dosa",
    slug: "onion-dosa",
    description: "Crispy dosa layered with finely chopped sweet red onions and roasted green chillies, cooked to a golden crunch.",
    price: 35,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "5-7 mins",
    portionSize: "1 Onion Studded Dosa",
    ingredients: "Dosa batter, Diced onions, Green chillies",
    displayOrder: 12,
  },
  {
    id: "masala-dosa",
    name: "Masala Dosa",
    slug: "masala-dosa",
    description: "Crisp golden dosa filled with our aromatic spiced potato and onion mash with mustard seed tempering.",
    price: 40,
    image: "/butter-masala-dosa.jpg",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "5-7 mins",
    portionSize: "1 Spiced Potato Masala Dosa",
    ingredients: "Dosa batter, Spiced potato palya, Mustard, Curry leaves",
    displayOrder: 13,
  },
  {
    id: "plain-pesara",
    name: "Plain Pesara",
    slug: "plain-pesara",
    description: "Authentic Andhra green gram (moong dal) pesarattu spread wafer-thin and roasted crisp on high flame.",
    price: 30,
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "5-7 mins",
    portionSize: "1 Crispy Moong Crepe",
    ingredients: "Soaked whole moong dal, Cumin, Ginger",
    displayOrder: 14,
  },
  {
    id: "onion-pesara",
    name: "Onion Pesara",
    slug: "onion-pesara",
    description: "Protein-rich green gram pesarattu studded with crunchy diced onions, cumin, and ginger slices.",
    price: 35,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "5-7 mins",
    portionSize: "1 Onion Topped Pesarattu",
    ingredients: "Green gram batter, Onions, Ginger, Cumin",
    displayOrder: 15,
  },
  {
    id: "masala-pesara",
    name: "Masala Pesara",
    slug: "masala-pesara",
    description: "Healthy moong dal pesarattu generously stuffed with savory spiced potato masala filling.",
    price: 40,
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "6-8 mins",
    portionSize: "1 Potato Stuffed Pesarattu",
    ingredients: "Green gram, Potato masala, Ginger",
    displayOrder: 16,
  },
  {
    id: "upma-pesara",
    name: "Upma Pesara",
    slug: "upma-pesara",
    description: "The royal Andhra MLA Pesarattu: crispy whole moong crepe stuffed with piping hot, rich ghee rava upma.",
    price: 50,
    image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "6-8 mins",
    portionSize: "1 Jumbo MLA Upma Pesarattu",
    ingredients: "Green gram batter, Ghee rava upma, Ginger chutney",
    displayOrder: 17,
  },
  {
    id: "ghee-karam",
    name: "Ghee Karam Dosa",
    slug: "ghee-karam",
    description: "Upahar's legendary crown jewel: thin crispy crepe smeared with fiery red garlic karam chutney and roasted in pure ghee.",
    price: 45,
    image: "/ghee-karam-dosa.jpg",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: true,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "5-7 mins",
    portionSize: "1 Signature Ghee Karam Dosa",
    ingredients: "Dosa batter, Pure Desi Ghee, Red garlic karam",
    displayOrder: 18,
  },
  {
    id: "ghee-karam-masala",
    name: "Ghee Karam Masala",
    slug: "ghee-karam-masala",
    description: "The ultimate combination of spicy red garlic karam, rich aromatic ghee, and seasoned potato masala mash.",
    price: 50,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: true,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "6-8 mins",
    portionSize: "1 Loaded Ghee Karam Masala Dosa",
    ingredients: "Dosa batter, Ghee, Karam paste, Potato mash",
    displayOrder: 19,
  },
  {
    id: "set-dosa",
    name: "Set Dosa",
    slug: "set-dosa",
    description: "Stack of thick, soft, spongy and melt-in-the-mouth dosas served with creamy coconut chutney and saggu.",
    price: 45,
    image: "https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "5-7 mins",
    portionSize: "Stack of 3 Spongy Dosas",
    ingredients: "Poha rice batter, Coconut chutney, Saggu",
    displayOrder: 20,
  },
  {
    id: "uttapam",
    name: "Uttapam",
    slug: "uttapam",
    description: "Thick savory pancake cooked slowly on cast-iron tawa with onions, green chillies, tomatoes, and cilantro topping.",
    price: 45,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "6-8 mins",
    portionSize: "1 Thick Veggie Savory Uttapam",
    ingredients: "Thick batter, Onions, Tomatoes, Coriander",
    displayOrder: 21,
  },
  {
    id: "panner-dosa",
    name: "Panner Dosa",
    slug: "panner-dosa",
    description: "Golden crispy crepe loaded with freshly grated soft dairy paneer, mild spices, and fresh herbs.",
    price: 55,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "6-8 mins",
    portionSize: "1 Grated Paneer Crepe",
    ingredients: "Dosa batter, Fresh paneer, Onion, Spices",
    displayOrder: 22,
  },
  {
    id: "corn-dosa",
    name: "Corn Dosa",
    slug: "corn-dosa",
    description: "Crunchy golden dosa filled with sweet juicy corn kernels sautéed with butter and delicate spices.",
    price: 50,
    image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "5-7 mins",
    portionSize: "1 Sweet Corn Filled Dosa",
    ingredients: "Dosa batter, Sweet corn, Butter, Herbs",
    displayOrder: 23,
  },
  {
    id: "chees-dosa",
    name: "Chees Dosa",
    slug: "chees-dosa",
    description: "Decadent crisp dosa overflowing with gooey melted cheese, making every bite rich and savory.",
    price: 60,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "5-7 mins",
    portionSize: "1 Melted Cheese Filled Dosa",
    ingredients: "Dosa batter, Melted cheese blend, Herbs",
    displayOrder: 24,
  },
  {
    id: "panner-cheese-dosa",
    name: "Panner Cheese Dosa",
    slug: "panner-cheese-dosa",
    description: "The ultimate luxury indulgence: generously filled with grated cottage paneer and molten cheese on a crispy crepe.",
    price: 80,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "7-9 mins",
    portionSize: "1 Loaded Paneer & Cheese Crepe",
    ingredients: "Dosa batter, Paneer, Molten cheese, Spices",
    displayOrder: 25,
  },
  {
    id: "corn-cheese-dosa",
    name: "Corn Cheese Dosa",
    slug: "corn-cheese-dosa",
    description: "Crisp dosa filled with the harmonious pair of tender sweet corn and melting creamy cheese.",
    price: 70,
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: false,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "6-8 mins",
    portionSize: "1 Sweet Corn & Gooey Cheese Dosa",
    ingredients: "Dosa batter, Sweet corn, Melted cheese",
    displayOrder: 26,
  },
  {
    id: "schezwan-dosa",
    name: "Schezwan Dosa",
    slug: "schezwan-dosa",
    description: "Crispy South Indian crepe smeared with fiery Indo-Chinese Schezwan sauce and sautéed spring veggies.",
    price: 50,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-dosa",
    category: FALLBACK_CATEGORIES[1],
    isVeg: true,
    isSpicy: true,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "5-7 mins",
    portionSize: "1 Spicy Schezwan Dosa",
    ingredients: "Dosa batter, Schezwan sauce, Veggies",
    displayOrder: 27,
  },

  // =========================================================================
  // 3. ONLY EVENING (Exact Menu Board Tariff: upahar_tiffins_menu.jpg)
  // =========================================================================
  {
    id: "chapati-2",
    name: "Chapati (2)",
    slug: "chapati-2",
    description: "Two freshly rolled, soft whole wheat chapatis roasted over open flame, served with flavorful curry.",
    price: 55,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-evening",
    category: FALLBACK_CATEGORIES[2],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "5-7 mins",
    portionSize: "2 Hot Soft Chapatis + Curry",
    ingredients: "Whole wheat flour, Daily curry",
    displayOrder: 28,
  },
  {
    id: "paratha-2",
    name: "Paratha (2)",
    slug: "paratha-2",
    description: "Two golden, flaky and multi-layered tawa parathas cooked with ghee and served with rich curry.",
    price: 55,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-evening",
    category: FALLBACK_CATEGORIES[2],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "6-8 mins",
    portionSize: "2 Layered Parathas + Curry",
    ingredients: "Layered dough, Ghee, Curry",
    displayOrder: 29,
  },

  // =========================================================================
  // 4. VEG NOODLES (Exact Menu Card Tariff: upahar_fastfood_menu.jpg)
  // =========================================================================
  {
    id: "veg-noodles",
    name: "Veg Noodles",
    slug: "veg-noodles",
    description: "Steaming wok-tossed noodles with shredded cabbage, crunchy carrots, capsicum, and aromatic soy garlic seasonings.",
    price: 60,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-veg-noodles",
    category: FALLBACK_CATEGORIES[3],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "8-10 mins",
    portionSize: "1 Full Plate Wok Noodles",
    ingredients: "Noodles, Cabbage, Carrot, Capsicum, Soy",
    displayOrder: 30,
  },
  {
    id: "veg-manchurian-noodles",
    name: "Veg Manchurian Noodles",
    slug: "veg-manchurian-noodles",
    description: "Wok noodles combined with savory fried vegetable Manchurian dumplings tossed in a rich tangy glaze.",
    price: 90,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-veg-noodles",
    category: FALLBACK_CATEGORIES[3],
    isVeg: true,
    isSpicy: true,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "10-12 mins",
    portionSize: "1 Loaded Plate with Manchurian Balls",
    ingredients: "Noodles, Veg Manchurian dumplings, Garlic, Scallions",
    displayOrder: 31,
  },
  {
    id: "schezwan-veg-noodles",
    name: "Schezwan Veg Noodles",
    slug: "schezwan-veg-noodles",
    description: "Fiery street-style noodles tossed in our home-made red chilli Schezwan sauce with crisp wok-fried vegetables.",
    price: 70,
    image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-veg-noodles",
    category: FALLBACK_CATEGORIES[3],
    isVeg: true,
    isSpicy: true,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "8-10 mins",
    portionSize: "1 Spicy Schezwan Platter",
    ingredients: "Noodles, Schezwan sauce, Wok vegetables",
    displayOrder: 32,
  },

  // =========================================================================
  // 5. NON-VEG NOODLES (Exact Menu Card Tariff: upahar_fastfood_menu.jpg)
  // =========================================================================
  {
    id: "chicken-noodles",
    name: "Chicken Noodles",
    slug: "chicken-noodles",
    description: "High-flame wok tossed noodles with tender spiced chicken chunks, eggs, and crisp bell peppers in garlic sauce.",
    price: 100,
    image: "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-nonveg-noodles",
    category: FALLBACK_CATEGORIES[4],
    isVeg: false,
    isSpicy: false,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "10-12 mins",
    portionSize: "1 Plate with Spiced Chicken",
    ingredients: "Noodles, Tender chicken, Egg, Garlic sauce",
    displayOrder: 33,
  },
  {
    id: "egg-noodles",
    name: "Egg Noodles",
    slug: "egg-noodles",
    description: "Noodles scrambled on high heat with fluffy eggs, chopped onions, cabbage, and savory Chinese spices.",
    price: 80,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-nonveg-noodles",
    category: FALLBACK_CATEGORIES[4],
    isVeg: false,
    isSpicy: false,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "8-10 mins",
    portionSize: "1 Plate Egg Scrambled Noodles",
    ingredients: "Noodles, Farm eggs, Cabbage, Pepper",
    displayOrder: 34,
  },
  {
    id: "egg-manchurian-noodles",
    name: "Egg Manchurian Noodles",
    slug: "egg-manchurian-noodles",
    description: "Scrambled egg noodles tossed together with crispy Manchurian balls in an aromatic garlic glaze.",
    price: 120,
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-nonveg-noodles",
    category: FALLBACK_CATEGORIES[4],
    isVeg: false,
    isSpicy: true,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "10-12 mins",
    portionSize: "1 Loaded Egg Manchurian Combo",
    ingredients: "Noodles, Farm eggs, Manchurian balls, Garlic",
    displayOrder: 35,
  },

  // =========================================================================
  // 6. VEG FRIED RICE (Exact Menu Card Tariff: upahar_fastfood_menu.jpg)
  // =========================================================================
  {
    id: "veg-fried-rice",
    name: "Veg Fried Rice",
    slug: "veg-fried-rice",
    description: "Fluffy basmati grains wok-fried on intense heat with green peas, diced carrots, beans, and light soy seasoning.",
    price: 80,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-veg-rice",
    category: FALLBACK_CATEGORIES[5],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "8-10 mins",
    portionSize: "1 Full Plate Veg Fried Rice",
    ingredients: "Basmati rice, Green peas, Carrots, Spring onions",
    displayOrder: 36,
  },
  {
    id: "corn-fried-rice",
    name: "Corn Fried Rice",
    slug: "corn-fried-rice",
    description: "Aromatic fried rice packed with sweet golden corn kernels and crisp garden greens.",
    price: 90,
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-veg-rice",
    category: FALLBACK_CATEGORIES[5],
    isVeg: true,
    isSpicy: false,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "8-10 mins",
    portionSize: "1 Plate Sweet Corn Rice",
    ingredients: "Basmati rice, Sweet corn, Garlic, White pepper",
    displayOrder: 37,
  },
  {
    id: "paneer-fried-rice",
    name: "Paneer Fried Rice",
    slug: "paneer-fried-rice",
    description: "Fragrant fried rice loaded with golden pan-seared paneer cubes and crunchy vegetables in Chinese wok seasoning.",
    price: 120,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-veg-rice",
    category: FALLBACK_CATEGORIES[5],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "10-12 mins",
    portionSize: "1 Loaded Paneer Rice Plate",
    ingredients: "Basmati rice, Dairy paneer cubes, Capsicum, Soy",
    displayOrder: 38,
  },
  {
    id: "baby-corn-fried-rice",
    name: "Baby Corn Fried Rice",
    slug: "baby-corn-fried-rice",
    description: "Wok-fried rice with crunchy sliced baby corn, bell peppers, and scallions in light garlic pepper sauce.",
    price: 120,
    image: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-veg-rice",
    category: FALLBACK_CATEGORIES[5],
    isVeg: true,
    isSpicy: false,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "10-12 mins",
    portionSize: "1 Plate Baby Corn Rice",
    ingredients: "Basmati rice, Tender baby corn, Bell peppers",
    displayOrder: 39,
  },
  {
    id: "all-mix-fried-rice",
    name: "All Mix Fried Rice",
    slug: "all-mix-fried-rice",
    description: "The grand vegetarian feast: wok-tossed with paneer, baby corn, sweet corn, mushrooms, and mixed veggies.",
    price: 150,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-veg-rice",
    category: FALLBACK_CATEGORIES[5],
    isVeg: true,
    isSpicy: false,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "10-14 mins",
    portionSize: "1 Jumbo Mixed Special Platter",
    ingredients: "Basmati rice, Paneer, Baby corn, Sweet corn, Veggies",
    displayOrder: 40,
  },

  // =========================================================================
  // 7. NON-VEG FRIED RICE (Exact Menu Card Tariff: upahar_fastfood_menu.jpg)
  // =========================================================================
  {
    id: "egg-fried-rice",
    name: "Egg Fried Rice",
    slug: "egg-fried-rice",
    description: "Street-style fried rice scrambled with farm eggs, sliced onions, white pepper, and scallions on roaring heat.",
    price: 100,
    image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-nonveg-rice",
    category: FALLBACK_CATEGORIES[6],
    isVeg: false,
    isSpicy: false,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "8-10 mins",
    portionSize: "1 Plate Egg Scrambled Rice",
    ingredients: "Basmati rice, Farm fresh eggs, Onions, White pepper",
    displayOrder: 41,
  },
  {
    id: "chicken-fried-rice",
    name: "Chicken Fried Rice",
    slug: "chicken-fried-rice",
    description: "Classic favorite: basmati rice tossed with spiced succulent chicken chunks, eggs, and crispy wok vegetables.",
    price: 120,
    image: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-nonveg-rice",
    category: FALLBACK_CATEGORIES[6],
    isVeg: false,
    isSpicy: false,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "10-12 mins",
    portionSize: "1 Hearty Chicken Rice Plate",
    ingredients: "Basmati rice, Tender chicken chunks, Egg, Veggies",
    displayOrder: 42,
  },
  {
    id: "chilli-chicken-fried-rice",
    name: "Chilli Chicken Fried Rice",
    slug: "chilli-chicken-fried-rice",
    description: "Deluxe combo: aromatic fried rice served with fiery, saucy Indo-Chinese Chilli Chicken topping.",
    price: 210,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-nonveg-rice",
    category: FALLBACK_CATEGORIES[6],
    isVeg: false,
    isSpicy: true,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "12-15 mins",
    portionSize: "1 Grand Combo Feast Platter",
    ingredients: "Basmati fried rice, Chilli chicken, Green chillies, Soy",
    displayOrder: 43,
  },

  // =========================================================================
  // 8. VEG STARTERS (Exact Menu Card Tariff: upahar_fastfood_menu.jpg)
  // =========================================================================
  {
    id: "veg-manchurian",
    name: "Veg Manchurian",
    slug: "veg-manchurian",
    description: "Crispy fried vegetable dumplings tossed in tangy, spicy dark soy garlic sauce with chopped spring onions.",
    price: 80,
    image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-veg-starters",
    category: FALLBACK_CATEGORIES[7],
    isVeg: true,
    isSpicy: true,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "10-12 mins",
    portionSize: "1 Plate Manchurian Balls (8-10 pcs)",
    ingredients: "Cabbage, Carrots, Garlic, Dark soy, Scallions",
    displayOrder: 44,
  },
  {
    id: "paneer-manchurian",
    name: "Paneer Manchurian",
    slug: "paneer-manchurian",
    description: "Golden batter-fried paneer cubes tossed in aromatic Manchurian glaze with ginger, garlic, and chillies.",
    price: 120,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-veg-starters",
    category: FALLBACK_CATEGORIES[7],
    isVeg: true,
    isSpicy: true,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "10-12 mins",
    portionSize: "1 Plate Paneer Manchurian",
    ingredients: "Dairy paneer, Manchurian sauce, Spring onions",
    displayOrder: 45,
  },
  {
    id: "chilli-paneer",
    name: "Chilli Paneer",
    slug: "chilli-paneer",
    description: "Crispy paneer cubes stir-fried with chunky capsicum, onions, slit green chillies, and savory dark soy sauce.",
    price: 130,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-veg-starters",
    category: FALLBACK_CATEGORIES[7],
    isVeg: true,
    isSpicy: true,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "10-12 mins",
    portionSize: "1 Plate Chilli Paneer Dry",
    ingredients: "Paneer, Bell peppers, Red onions, Green chillies",
    displayOrder: 46,
  },

  // =========================================================================
  // 9. NON-VEG STARTERS (Exact Menu Card Tariff: upahar_fastfood_menu.jpg)
  // =========================================================================
  {
    id: "chicken-manchurian",
    name: "Chicken Manchurian",
    slug: "chicken-manchurian",
    description: "Juicy chicken bites tossed in rich, savory garlic-soy Indo-Chinese Manchurian sauce with scallions.",
    price: 120,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-nonveg-starters",
    category: FALLBACK_CATEGORIES[8],
    isVeg: false,
    isSpicy: true,
    isBestseller: true,
    isSignature: false,
    isAvailable: true,
    prepTime: "12-14 mins",
    portionSize: "1 Plate Chicken Manchurian Dry",
    ingredients: "Boneless chicken, Garlic, Soy sauce, Scallions",
    displayOrder: 47,
  },
  {
    id: "chilli-chicken",
    name: "Chilli Chicken",
    slug: "chilli-chicken",
    description: "Fiery Indo-Chinese boneless chicken tossed with crunchy capsicum, red onions, and hot green chillies.",
    price: 130,
    image: "https://images.unsplash.com/photo-1527477321055-436158a2b0a5?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-nonveg-starters",
    category: FALLBACK_CATEGORIES[8],
    isVeg: false,
    isSpicy: true,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "12-14 mins",
    portionSize: "1 Plate Spicy Chilli Chicken",
    ingredients: "Marinated chicken, Green chillies, Bell peppers, Dark soy",
    displayOrder: 48,
  },
  {
    id: "egg-manchurian",
    name: "Egg Manchurian",
    slug: "egg-manchurian",
    description: "Crispy battered farm egg wedges tossed in spicy, tangy Manchurian sauce with garlic and spring onions.",
    price: 100,
    image: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-nonveg-starters",
    category: FALLBACK_CATEGORIES[8],
    isVeg: false,
    isSpicy: true,
    isBestseller: false,
    isSignature: false,
    isAvailable: true,
    prepTime: "10-12 mins",
    portionSize: "1 Plate Egg Manchurian",
    ingredients: "Farm eggs, Manchurian batter, Garlic, Scallions",
    displayOrder: 49,
  },
  {
    id: "mughlai-chicken",
    name: "Mughlai Chicken",
    slug: "mughlai-chicken",
    description: "Rich, royal preparation of tender chicken pieces cooked in aromatic spices, egg glaze, and fresh herbs.",
    price: 150,
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-nonveg-starters",
    category: FALLBACK_CATEGORIES[8],
    isVeg: false,
    isSpicy: true,
    isBestseller: true,
    isSignature: true,
    isAvailable: true,
    prepTime: "14-16 mins",
    portionSize: "1 Plate Royal Mughlai Starter",
    ingredients: "Tender chicken, Egg, Mughlai spices, Herbs",
    displayOrder: 50,
  },
];
