import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding UPAHAR TIFFINS AND FAST FOOD database with authentic menu items...");

  // 1. Admin User
  const passwordHash = await bcrypt.hash("admin123", 10);
  await prisma.adminUser.upsert({
    where: { email: "admin@upahar.com" },
    update: { passwordHash, name: "Upahar Management" },
    create: {
      name: "Upahar Management",
      email: "admin@upahar.com",
      passwordHash,
      role: "ADMIN",
    },
  });

  // 2. Restaurant Setting
  await prisma.restaurantSetting.upsert({
    where: { id: "default" },
    update: {
      restaurantName: "UPAHAR TIFFINS AND FAST FOOD",
      tagline: "Sunrise to Sunset • Good Food • Good Mood",
      heroHeadline: "Upahar Tiffins & Fast Food",
      heroSubheadline: "Morning Tiffins 6:00 AM – 10:00 AM • Evening Fast Food 6:00 PM – 10:30 PM. Handcrafted fresh with pure quality ingredients.",
      storyTitle: "Authentic Flavours & Sizzling Delights in Sangivalasa",
      storyText: "Located at 1-1, Sangivalasa, ANITS College Road, beside SBI, UPAHAR is the community's favorite destination for steaming morning tiffins and sizzling evening fast food. From golden ghee karam dosas and button idlys to wok-tossed Schezwan noodles and crispy Manchurian, we cook fresh per order.",
      phone: "+91 9885455342",
      email: "contact@upahar.com",
      whatsappNumber: "919885455342",
      address: "1-1, Sangivalasa, ANITS College Road, Beside SBI, Visakhapatnam, Andhra Pradesh 531162",
      landmark: "Beside SBI, ANITS College Road, Sangivalasa",
      googleMapsUrl: "https://maps.app.goo.gl/6611R6FD1JZagSJt9",
      openingTime: "06:00",
      closingTime: "22:30",
      breakfastHours: "6:00 AM – 10:00 AM",
      lunchHours: "Kitchen Prep (10:00 AM – 6:00 PM)",
      eveningHours: "6:00 PM – 10:30 PM",
      dinnerHours: "6:00 PM – 10:30 PM",
      isEmergencyClosed: false,
      instagramUrl: "https://www.instagram.com/upahar_07/",
      pureVegPledge: "Hygienic & Safe • Fresh Ingredients • Door Delivery Available (Min Order)",
    },
    create: {
      id: "default",
      restaurantName: "UPAHAR TIFFINS AND FAST FOOD",
      tagline: "Sunrise to Sunset • Good Food • Good Mood",
      heroHeadline: "Upahar Tiffins & Fast Food",
      heroSubheadline: "Morning Tiffins 6:00 AM – 10:00 AM • Evening Fast Food 6:00 PM – 10:30 PM. Handcrafted fresh with pure quality ingredients.",
      storyTitle: "Authentic Flavours & Sizzling Delights in Sangivalasa",
      storyText: "Located at 1-1, Sangivalasa, ANITS College Road, beside SBI, UPAHAR is the community's favorite destination for steaming morning tiffins and sizzling evening fast food. From golden ghee karam dosas and button idlys to wok-tossed Schezwan noodles and crispy Manchurian, we cook fresh per order.",
      phone: "+91 9885455342",
      email: "contact@upahar.com",
      whatsappNumber: "919885455342",
      address: "1-1, Sangivalasa, ANITS College Road, Beside SBI, Visakhapatnam, Andhra Pradesh 531162",
      landmark: "Beside SBI, ANITS College Road, Sangivalasa",
      googleMapsUrl: "https://maps.app.goo.gl/6611R6FD1JZagSJt9",
      openingTime: "06:00",
      closingTime: "22:30",
      breakfastHours: "6:00 AM – 10:00 AM",
      lunchHours: "Kitchen Prep (10:00 AM – 6:00 PM)",
      eveningHours: "6:00 PM – 10:30 PM",
      dinnerHours: "6:00 PM – 10:30 PM",
      isEmergencyClosed: false,
      instagramUrl: "https://www.instagram.com/upahar_07/",
      pureVegPledge: "Hygienic & Safe • Fresh Ingredients • Door Delivery Available (Min Order)",
    },
  });

  // 3. Clear existing food items to seed authentic menu
  await prisma.foodItem.deleteMany({});
  await prisma.category.deleteMany({});

  // 4. Categories Data
  const categories = [
    {
      name: "Tiffins & Breakfast",
      slug: "tiffins",
      description: "Steaming hot idlys, crunchy wada, fluffy pooris, and golden bondas served with freshly churned chutneys and piping hot sambar.",
      icon: "Sparkles",
      displayOrder: 1,
    },
    {
      name: "Dosa Craft",
      slug: "dosa",
      description: "Crispy golden dosas roasted on heavy cast-iron tavas with desi ghee, onion, paneer, and fiery karam masala.",
      icon: "Flame",
      displayOrder: 2,
    },
    {
      name: "Evening Specials",
      slug: "evening-specials",
      description: "Hot soft chapatis and flaky layered parathas served exclusively during evening hours.",
      icon: "UtensilsCrossed",
      displayOrder: 3,
    },
    {
      name: "Veg & Non-Veg Noodles",
      slug: "noodles",
      description: "Sizzling high-flame wok noodles tossed with fresh veggies, egg, succulent chicken, and chef's spicy sauces.",
      icon: "Soup",
      displayOrder: 4,
    },
    {
      name: "Veg & Non-Veg Fried Rice",
      slug: "fried-rice",
      description: "Fragrant basmati rice wok-fried with crisp garden vegetables, paneer, egg, or spicy chilli chicken.",
      icon: "Flame",
      displayOrder: 5,
    },
    {
      name: "Starters & Appetizers",
      slug: "starters",
      description: "Irresistible crispy Manchurian, spicy chilli paneer, and rich Mughlai chicken starters.",
      icon: "Sparkles",
      displayOrder: 6,
    },
  ];

  const createdCategories: Record<string, string> = {};
  for (const cat of categories) {
    const created = await prisma.category.create({ data: cat });
    createdCategories[cat.slug] = created.id;
  }

  // 5. Authentic Food Items from the Menus
  const items = [
    // --- TIFFINS (10 Items) ---
    {
      name: "Idly (4)",
      slug: "idly-4",
      description: "Four cloud-soft steamed rice and urad dal cakes, served piping hot with freshly ground peanut chutney and aromatic drumstick sambar.",
      price: 30,
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["tiffins"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "2-3 mins",
      portionSize: "4 Steamed Idlis + 2 Chutneys + Sambar",
      ingredients: "Fermented rice batter, Urad dal, Drumstick sambar, Peanut coconut chutney",
      displayOrder: 1,
    },
    {
      name: "Tatte Idly",
      slug: "tatte-idly",
      description: "Signature wide, fluffy plate-shaped tatte idly steamed to spongy tenderness and served steaming with fragrant podi and sambar.",
      price: 25,
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["tiffins"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: true,
      prepTime: "3-5 mins",
      portionSize: "1 Jumbo Tatte Idly + Chutneys",
      ingredients: "Stone ground rice batter, Coconut chutney, Spicy allam chutney",
      displayOrder: 2,
    },
    {
      name: "Sambar Idly (3)",
      slug: "sambar-idly-3",
      description: "Three soft idlis immersed completely in a bowl of piping hot, spiced drumstick sambar with a touch of fresh coriander.",
      price: 30,
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["tiffins"],
      isVeg: true,
      isSpicy: true,
      isBestseller: true,
      isSignature: false,
      prepTime: "2-3 mins",
      portionSize: "3 Idlis soaked in generous bowl of sambar",
      ingredients: "Steamed idlis, Lentil vegetable sambar, Mustard tempering, Curry leaves",
      displayOrder: 3,
    },
    {
      name: "Citti Idly",
      slug: "citti-idly",
      description: "Mini button idlis steamed fresh and served with generous helpings of coconut and ginger chutney.",
      price: 40,
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["tiffins"],
      isVeg: true,
      isSpicy: false,
      isBestseller: false,
      isSignature: false,
      prepTime: "3-5 mins",
      portionSize: "Bowl of mini button idlis with sambar",
      ingredients: "Rice, Urad dal, Chutneys, Drumstick sambar",
      displayOrder: 4,
    },
    {
      name: "Ghee Podi Idly (3)",
      slug: "ghee-podi-idly-3",
      description: "Three steaming idlis tossed generously in authentic roasted gun powder (podi) and pure fragrant ghee.",
      price: 35,
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["tiffins"],
      isVeg: true,
      isSpicy: true,
      isBestseller: true,
      isSignature: true,
      prepTime: "3-5 mins",
      portionSize: "3 Idlis with Ghee Podi coating",
      ingredients: "Steamed idlis, Pure Desi Ghee, Roasted spiced karam podi",
      displayOrder: 5,
    },
    {
      name: "Tawa Idly",
      slug: "tawa-idly",
      description: "Idlis sliced and stir-fried on a roaring hot cast-iron tawa with onions, curry leaves, crushed spices, and ghee.",
      price: 50,
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["tiffins"],
      isVeg: true,
      isSpicy: true,
      isBestseller: false,
      isSignature: true,
      prepTime: "5-7 mins",
      portionSize: "Plate of spiced tawa stir-fried idly pieces",
      ingredients: "Idly cubes, Onions, Green chillies, Ghee, Tawa masala",
      displayOrder: 6,
    },
    {
      name: "Bonda (4)",
      slug: "bonda-4",
      description: "Crisp on the outside, feather-light and fluffy inside Mysore style bondas served with ginger chutney.",
      price: 30,
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["tiffins"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "3-5 mins",
      portionSize: "4 Golden crisp bondas with chutneys",
      ingredients: "Fermented batter, Cumin seeds, Ginger, Green chillies",
      displayOrder: 7,
    },
    {
      name: "Poori (2)",
      slug: "poori-2",
      description: "Two golden puffed deep-fried wheat pooris served with flavorful potato kurma/saggu and chutney.",
      price: 30,
      image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["tiffins"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "4-6 mins",
      portionSize: "2 Hot puffed pooris + Spiced potato masala",
      ingredients: "Whole wheat flour, Potato kurma, Onion masala",
      displayOrder: 8,
    },
    {
      name: "Wada (3)",
      slug: "wada-3",
      description: "Three deep golden, crunchy on the exterior, fluffy within medu wadas tempered with black pepper and curry leaves.",
      price: 30,
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["tiffins"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "3-5 mins",
      portionSize: "3 Crispy medu wadas + Chutney + Sambar",
      ingredients: "Urad dal, Whole peppercorns, Ginger, Curry leaves",
      displayOrder: 9,
    },
    {
      name: "Sambar Wada (2)",
      slug: "sambar-wada-2",
      description: "Two crisp wadas submerged in steaming hot drumstick sambar until tender, garnished with fresh onions and coriander.",
      price: 30,
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["tiffins"],
      isVeg: true,
      isSpicy: true,
      isBestseller: false,
      isSignature: false,
      prepTime: "2-4 mins",
      portionSize: "2 Wadas in a rich bowl of sambar",
      ingredients: "Crisp wadas, Spiced sambar, Chopped fresh onions",
      displayOrder: 10,
    },

    // --- DOSA CRAFT (17 Items) ---
    {
      name: "Plain Dosa",
      slug: "plain-dosa",
      description: "Traditional thin golden crepe roasted on cast iron with fragrant oil and ghee, served with coconut chutney & sambar.",
      price: 30,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "4-6 mins",
      portionSize: "1 Large crisp dosa + 2 Chutneys + Sambar",
      ingredients: "Stone-ground fermented rice and urad dal batter",
      displayOrder: 11,
    },
    {
      name: "Onion Dosa",
      slug: "onion-dosa",
      description: "Crispy dosa layered with finely chopped sweet red onions and roasted green chillies, cooked to a golden crunch.",
      price: 35,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: false,
      isSignature: false,
      prepTime: "5-7 mins",
      portionSize: "1 Large onion-studded dosa",
      ingredients: "Dosa batter, Diced onions, Green chillies, Curry leaves",
      displayOrder: 12,
    },
    {
      name: "Masala Dosa",
      slug: "masala-dosa",
      description: "Crisp golden dosa filled with our aromatic spiced potato and onion mash with mustard seed tempering.",
      price: 40,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "5-7 mins",
      portionSize: "1 Classic spiced potato masala filled dosa",
      ingredients: "Dosa batter, Spiced potato palya, Mustard seeds, Curry leaves",
      displayOrder: 13,
    },
    {
      name: "Plain Pesara",
      slug: "plain-pesara",
      description: "Authentic Andhra green gram (moong dal) pesarattu spread wafer-thin and roasted crisp on high flame.",
      price: 30,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: false,
      isSignature: false,
      prepTime: "5-7 mins",
      portionSize: "1 Crispy whole moong crepe + Allam ginger chutney",
      ingredients: "Soaked whole moong dal, Cumin seeds, Ginger",
      displayOrder: 14,
    },
    {
      name: "Onion Pesara",
      slug: "onion-pesara",
      description: "Protein-rich green gram pesarattu studded with crunchy diced onions, cumin, and ginger slices.",
      price: 35,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "5-7 mins",
      portionSize: "1 Onion topped pesarattu + Allam chutney",
      ingredients: "Green gram batter, Onions, Ginger, Cumin seeds",
      displayOrder: 15,
    },
    {
      name: "Masala Pesara",
      slug: "masala-pesara",
      description: "Healthy moong dal pesarattu generously stuffed with savory spiced potato masala filling.",
      price: 40,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: false,
      isSignature: false,
      prepTime: "6-8 mins",
      portionSize: "1 Pesarattu with spiced potato filling",
      ingredients: "Green gram, Potato masala, Ginger, Green chillies",
      displayOrder: 16,
    },
    {
      name: "Upma Pesara",
      slug: "upma-pesara",
      description: "The royal Andhra MLA Pesarattu: crispy whole moong crepe stuffed with piping hot, rich ghee rava upma.",
      price: 50,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: true,
      prepTime: "6-8 mins",
      portionSize: "1 Jumbo MLA Pesarattu filled with hot upma",
      ingredients: "Green gram batter, Ghee rava upma, Ginger chutney",
      displayOrder: 17,
    },
    {
      name: "Ghee Karam Dosa",
      slug: "ghee-karam-dosa",
      description: "Upahar's legendary crown jewel: thin crispy crepe smeared with fiery red garlic karam chutney and roasted in pure ghee.",
      price: 45,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: true,
      isBestseller: true,
      isSignature: true,
      prepTime: "5-7 mins",
      portionSize: "1 Signature Ghee Karam Dosa + Chutneys",
      ingredients: "Dosa batter, Pure Desi Ghee, Spicy garlic red chilli karam",
      displayOrder: 18,
    },
    {
      name: "Ghee Karam Masala Dosa",
      slug: "ghee-karam-masala-dosa",
      description: "The ultimate combination of spicy red garlic karam, rich aromatic ghee, and seasoned potato masala mash.",
      price: 50,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: true,
      isBestseller: true,
      isSignature: true,
      prepTime: "6-8 mins",
      portionSize: "1 Loaded Ghee Karam Masala Dosa",
      ingredients: "Dosa batter, Ghee, Spicy karam paste, Spiced potato filling",
      displayOrder: 19,
    },
    {
      name: "Set Dosa",
      slug: "set-dosa",
      description: "Stack of thick, soft, spongy and melt-in-the-mouth dosas served with creamy coconut chutney and vegetable saggu.",
      price: 45,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: false,
      isSignature: false,
      prepTime: "5-7 mins",
      portionSize: "Stack of 3 Spongy Soft Set Dosas",
      ingredients: "Poha rice batter, Fresh coconut chutney, Saggu",
      displayOrder: 20,
    },
    {
      name: "Uttapam",
      slug: "uttapam",
      description: "Thick savory pancake cooked slowly on cast-iron tawa with onions, green chillies, tomatoes, and cilantro topping.",
      price: 45,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: false,
      isSignature: false,
      prepTime: "6-8 mins",
      portionSize: "1 Thick vegetable topped savory uttapam",
      ingredients: "Thick dosa batter, Chopped onions, Tomatoes, Coriander",
      displayOrder: 21,
    },
    {
      name: "Paneer Dosa",
      slug: "paneer-dosa",
      description: "Golden crispy crepe loaded with freshly grated soft dairy paneer, mild spices, and fresh herbs.",
      price: 55,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "6-8 mins",
      portionSize: "1 Rich grated paneer stuffed crepe",
      ingredients: "Dosa batter, Fresh paneer, Onion, Special masala",
      displayOrder: 22,
    },
    {
      name: "Corn Dosa",
      slug: "corn-dosa",
      description: "Crunchy golden dosa filled with sweet juicy corn kernels sautéed with butter and delicate spices.",
      price: 50,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: false,
      isSignature: false,
      prepTime: "5-7 mins",
      portionSize: "1 Sweet corn filled crispy dosa",
      ingredients: "Dosa batter, Sweet corn kernels, Butter, Herbs",
      displayOrder: 23,
    },
    {
      name: "Cheese Dosa",
      slug: "cheese-dosa",
      description: "Decadent crisp dosa overflowing with gooey melted cheese, making every bite rich and savory.",
      price: 60,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "5-7 mins",
      portionSize: "1 Melted cheese filled golden dosa",
      ingredients: "Dosa batter, Melted cheese blend, Herbs",
      displayOrder: 24,
    },
    {
      name: "Paneer Cheese Dosa",
      slug: "paneer-cheese-dosa",
      description: "The ultimate luxury indulgence: generously filled with grated cottage paneer and molten cheese on a crispy tawa crepe.",
      price: 80,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: true,
      prepTime: "7-9 mins",
      portionSize: "1 Loaded paneer & melted cheese crepe",
      ingredients: "Dosa batter, Fresh paneer, Molten cheese, Spices",
      displayOrder: 25,
    },
    {
      name: "Corn Cheese Dosa",
      slug: "corn-cheese-dosa",
      description: "Crisp dosa filled with the harmonious pair of tender sweet corn and melting creamy cheese.",
      price: 70,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: false,
      isBestseller: false,
      isSignature: false,
      prepTime: "6-8 mins",
      portionSize: "1 Sweet corn & gooey cheese crepe",
      ingredients: "Dosa batter, Sweet corn, Melted cheese, Pepper",
      displayOrder: 26,
    },
    {
      name: "Schezwan Dosa",
      slug: "schezwan-dosa",
      description: "A fusion delight: crispy South Indian crepe smeared with fiery Indo-Chinese Schezwan sauce and sautéed spring veggies.",
      price: 50,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["dosa"],
      isVeg: true,
      isSpicy: true,
      isBestseller: false,
      isSignature: false,
      prepTime: "5-7 mins",
      portionSize: "1 Spicy Schezwan sauce tossed dosa",
      ingredients: "Dosa batter, Schezwan sauce, Shredded veggies",
      displayOrder: 27,
    },

    // --- EVENING SPECIALS (2 Items) ---
    {
      name: "Chapati (2)",
      slug: "chapati-2",
      description: "Two freshly rolled, soft whole wheat chapatis roasted over open flame, served with flavorful mixed vegetable curry.",
      price: 55,
      image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["evening-specials"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "5-7 mins",
      portionSize: "2 Hot soft chapatis + Daily vegetable curry",
      ingredients: "100% Whole wheat flour, Vegetable curry, Herbs",
      displayOrder: 28,
    },
    {
      name: "Paratha (2)",
      slug: "paratha-2",
      description: "Two golden, flaky and multi-layered tawa parathas cooked with ghee and served with rich vegetable curry.",
      price: 55,
      image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["evening-specials"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "6-8 mins",
      portionSize: "2 Flaky layered parathas + Curry",
      ingredients: "Layered dough, Ghee, Vegetable curry",
      displayOrder: 29,
    },

    // --- VEG & NON-VEG NOODLES (6 Items) ---
    {
      name: "Veg Noodles",
      slug: "veg-noodles",
      description: "Steaming wok-tossed noodles with shredded cabbage, crunchy carrots, capsicum, and aromatic soy garlic seasonings.",
      price: 60,
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["noodles"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "8-10 mins",
      portionSize: "1 Full plate wok-tossed noodles",
      ingredients: "Hakka noodles, Cabbage, Carrot, Capsicum, Soy sauce",
      displayOrder: 30,
    },
    {
      name: "Veg Manchurian Noodles",
      slug: "veg-manchurian-noodles",
      description: "Wok noodles combined with savory fried vegetable Manchurian dumplings tossed in a rich tangy gravy.",
      price: 90,
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["noodles"],
      isVeg: true,
      isSpicy: true,
      isBestseller: true,
      isSignature: true,
      prepTime: "10-12 mins",
      portionSize: "1 Loaded plate with Manchurian dumplings",
      ingredients: "Noodles, Veg Manchurian balls, Garlic, Spring onions",
      displayOrder: 31,
    },
    {
      name: "Schezwan Veg Noodles",
      slug: "schezwan-veg-noodles",
      description: "Fiery street-style noodles tossed in our home-made red chilli Schezwan sauce with crisp wok-fried vegetables.",
      price: 70,
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["noodles"],
      isVeg: true,
      isSpicy: true,
      isBestseller: false,
      isSignature: false,
      prepTime: "8-10 mins",
      portionSize: "1 Spicy Schezwan noodle platter",
      ingredients: "Noodles, Schezwan peppers, Garlic, Crunchy vegetables",
      displayOrder: 32,
    },
    {
      name: "Chicken Noodles",
      slug: "chicken-noodles",
      description: "High-flame wok tossed noodles with tender spiced chicken chunks, eggs, and crisp bell peppers in garlic sauce.",
      price: 100,
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["noodles"],
      isVeg: false,
      isSpicy: false,
      isBestseller: true,
      isSignature: true,
      prepTime: "10-12 mins",
      portionSize: "1 Hearty plate with tender chicken chunks",
      ingredients: "Noodles, Spiced chicken, Egg, Wok vegetables, Soy",
      displayOrder: 33,
    },
    {
      name: "Egg Noodles",
      slug: "egg-noodles",
      description: "Noodles scrambled on high heat with fluffy eggs, chopped onions, cabbage, and savory Chinese spices.",
      price: 80,
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["noodles"],
      isVeg: false,
      isSpicy: false,
      isBestseller: false,
      isSignature: false,
      prepTime: "8-10 mins",
      portionSize: "1 Plate egg-scrambled noodles",
      ingredients: "Noodles, Fresh farm eggs, Onion, Cabbage, Pepper",
      displayOrder: 34,
    },
    {
      name: "Egg Manchurian Noodles",
      slug: "egg-manchurian-noodles",
      description: "Scrambled egg noodles tossed together with crispy Manchurian balls in an aromatic garlic sauce.",
      price: 120,
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["noodles"],
      isVeg: false,
      isSpicy: true,
      isBestseller: false,
      isSignature: false,
      prepTime: "10-12 mins",
      portionSize: "1 Loaded egg and Manchurian noodle combo",
      ingredients: "Noodles, Farm eggs, Manchurian balls, Spring onions",
      displayOrder: 35,
    },

    // --- VEG & NON-VEG FRIED RICE (8 Items) ---
    {
      name: "Veg Fried Rice",
      slug: "veg-fried-rice",
      description: "Fluffy basmati grains wok-fried on intense heat with green peas, diced carrots, beans, and light soy seasoning.",
      price: 80,
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["fried-rice"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "8-10 mins",
      portionSize: "1 Full plate fragrant vegetable fried rice",
      ingredients: "Aromatic basmati rice, Green peas, Carrots, Spring onions",
      displayOrder: 36,
    },
    {
      name: "Corn Fried Rice",
      slug: "corn-fried-rice",
      description: "Aromatic fried rice packed with sweet golden corn kernels and crisp garden greens.",
      price: 90,
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["fried-rice"],
      isVeg: true,
      isSpicy: false,
      isBestseller: false,
      isSignature: false,
      prepTime: "8-10 mins",
      portionSize: "1 Plate sweet corn fried rice",
      ingredients: "Basmati rice, Sweet corn, Garlic, White pepper",
      displayOrder: 37,
    },
    {
      name: "Paneer Fried Rice",
      slug: "paneer-fried-rice",
      description: "Fragrant fried rice loaded with golden pan-seared paneer cubes and crunchy vegetables in Chinese wok seasoning.",
      price: 120,
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["fried-rice"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: true,
      prepTime: "10-12 mins",
      portionSize: "1 Hearty plate with golden paneer cubes",
      ingredients: "Basmati rice, Dairy paneer cubes, Capsicum, Soy sauce",
      displayOrder: 38,
    },
    {
      name: "Baby Corn Fried Rice",
      slug: "baby-corn-fried-rice",
      description: "Wok-fried rice with crunchy sliced baby corn, bell peppers, and scallions in light garlic pepper sauce.",
      price: 120,
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["fried-rice"],
      isVeg: true,
      isSpicy: false,
      isBestseller: false,
      isSignature: false,
      prepTime: "10-12 mins",
      portionSize: "1 Plate crispy baby corn fried rice",
      ingredients: "Basmati rice, Tender baby corn, Spring onions, Garlic",
      displayOrder: 39,
    },
    {
      name: "All Mix Fried Rice",
      slug: "all-mix-fried-rice",
      description: "The grand vegetarian feast: wok-tossed with paneer, baby corn, sweet corn, mushrooms, and mixed veggies.",
      price: 150,
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["fried-rice"],
      isVeg: true,
      isSpicy: false,
      isBestseller: true,
      isSignature: true,
      prepTime: "10-14 mins",
      portionSize: "1 Jumbo plate with assorted gourmet toppings",
      ingredients: "Basmati rice, Paneer, Baby corn, Sweet corn, Fresh vegetables",
      displayOrder: 40,
    },
    {
      name: "Egg Fried Rice",
      slug: "egg-fried-rice",
      description: "Street-style fried rice scrambled with farm eggs, sliced onions, white pepper, and scallions on roaring heat.",
      price: 100,
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["fried-rice"],
      isVeg: false,
      isSpicy: false,
      isBestseller: true,
      isSignature: false,
      prepTime: "8-10 mins",
      portionSize: "1 Plate egg scrambled fried rice",
      ingredients: "Basmati rice, Farm fresh eggs, Onions, White pepper",
      displayOrder: 41,
    },
    {
      name: "Chicken Fried Rice",
      slug: "chicken-fried-rice",
      description: "Classic favorite: basmati rice tossed with spiced succulent chicken chunks, eggs, and crispy wok vegetables.",
      price: 120,
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["fried-rice"],
      isVeg: false,
      isSpicy: false,
      isBestseller: true,
      isSignature: true,
      prepTime: "10-12 mins",
      portionSize: "1 Full plate chicken & egg fried rice",
      ingredients: "Basmati rice, Marinated chicken breast, Egg, Garlic, Soy",
      displayOrder: 42,
    },
    {
      name: "Chilli Chicken Fried Rice",
      slug: "chilli-chicken-fried-rice",
      description: "Premium specialty: wok-tossed egg fried rice served with generous portions of spicy Indo-Chinese chilli chicken.",
      price: 210,
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["fried-rice"],
      isVeg: false,
      isSpicy: true,
      isBestseller: true,
      isSignature: true,
      prepTime: "12-15 mins",
      portionSize: "1 Jumbo platter of Fried Rice + Spicy Chilli Chicken",
      ingredients: "Basmati rice, Crispy chilli chicken, Green chillies, Soy, Spring onions",
      displayOrder: 43,
    },

    // --- STARTERS & APPETIZERS (7 Items) ---
    {
      name: "Veg Manchurian",
      slug: "veg-manchurian",
      description: "Crispy fried vegetable balls tossed in ginger, garlic, green chillies, and savory dark soy Manchurian sauce.",
      price: 80,
      image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["starters"],
      isVeg: true,
      isSpicy: true,
      isBestseller: true,
      isSignature: false,
      prepTime: "8-10 mins",
      portionSize: "1 Plate crisp vegetable Manchurian balls",
      ingredients: "Minced cabbage, Carrot, Ginger, Garlic, Soy sauce",
      displayOrder: 44,
    },
    {
      name: "Paneer Manchurian",
      slug: "paneer-manchurian",
      description: "Succulent cubes of cottage cheese batter-fried crisp and coated in tangy, spicy Indo-Chinese Manchurian glaze.",
      price: 120,
      image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["starters"],
      isVeg: true,
      isSpicy: true,
      isBestseller: true,
      isSignature: true,
      prepTime: "10-12 mins",
      portionSize: "1 Plate golden paneer Manchurian",
      ingredients: "Dairy paneer cubes, Manchurian glaze, Scallions, Garlic",
      displayOrder: 45,
    },
    {
      name: "Chilli Paneer",
      slug: "chilli-paneer",
      description: "Fresh paneer wok-tossed with spicy green chillies, crunchy bell peppers, and rich chili garlic sauce.",
      price: 130,
      image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["starters"],
      isVeg: true,
      isSpicy: true,
      isBestseller: true,
      isSignature: true,
      prepTime: "10-12 mins",
      portionSize: "1 Sizzling plate chilli paneer",
      ingredients: "Paneer cubes, Green chillies, Diced capsicum, Onions",
      displayOrder: 46,
    },
    {
      name: "Chicken Manchurian",
      slug: "chicken-manchurian",
      description: "Crispy chicken pieces coated in seasoned cornstarch batter and sautéed in a rich garlic cilantro Manchurian glaze.",
      price: 120,
      image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["starters"],
      isVeg: false,
      isSpicy: true,
      isBestseller: true,
      isSignature: false,
      prepTime: "10-12 mins",
      portionSize: "1 Plate crispy glazed chicken Manchurian",
      ingredients: "Boneless chicken pieces, Manchurian sauce, Spring onions",
      displayOrder: 47,
    },
    {
      name: "Chilli Chicken",
      slug: "chilli-chicken",
      description: "Diner favorite: crisp fried boneless chicken tossed on high flame with slit green chillies, onions, and spicy red pepper sauce.",
      price: 130,
      image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["starters"],
      isVeg: false,
      isSpicy: true,
      isBestseller: true,
      isSignature: true,
      prepTime: "10-12 mins",
      portionSize: "1 Sizzling plate of spicy chilli chicken",
      ingredients: "Chicken cubes, Slit chillies, Garlic, Capsicum, Soy sauce",
      displayOrder: 48,
    },
    {
      name: "Egg Manchurian",
      slug: "egg-manchurian",
      description: "Boiled egg halves or egg batter fritters tossed in savory sweet and sour Manchurian glaze with spring onions.",
      price: 100,
      image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["starters"],
      isVeg: false,
      isSpicy: true,
      isBestseller: false,
      isSignature: false,
      prepTime: "8-10 mins",
      portionSize: "1 Plate egg Manchurian starter",
      ingredients: "Eggs, Manchurian gravy, Ginger, Garlic, Scallions",
      displayOrder: 49,
    },
    {
      name: "Mughlai Chicken",
      slug: "mughlai-chicken",
      description: "Rich, aromatic and mildly spiced royal Mughlai chicken starter seasoned with crushed cashews, cream, and green cardamom.",
      price: 150,
      image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
      categoryId: createdCategories["starters"],
      isVeg: false,
      isSpicy: false,
      isBestseller: true,
      isSignature: true,
      prepTime: "12-15 mins",
      portionSize: "1 Royal plate Mughlai chicken starter",
      ingredients: "Tender chicken, Cashew paste, Cream, Spices, Saffron touch",
      displayOrder: 50,
    },
  ];

  for (const item of items) {
    await prisma.foodItem.create({ data: item });
  }

  console.log(`Successfully seeded ${items.length} authentic dishes across ${categories.length} categories!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
